import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="coding blog, hunter blog,next js" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src='/mysc.js'></script> */}
      </Head>
      <Script src="/mysc.js" strategy='lazyOnload'></Script>
      <nav className={styles.mainnav}>
        <ul>
          <Link href="/">
            <li>Home</li>
          </Link>
          <Link href="/about">
            <li>About</li>
          </Link>
          <Link href="/blog">
            <li>Blogs</li>
          </Link>
          <Link href="/contact">
            <li>Contact</li>
          </Link>
        </ul>
      </nav>
      <div className={styles.mainHeading}>
        <h1>Hunting Coder</h1>
        <p>Search Create Solve and Repeat</p>
      </div>
      <div className={styles.BlogTemp}>
        <h2>Our Blogs</h2>
        <div>
          <h3>First Blog</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi quos optio quisquam. Architecto error odit mollitia quae tempora sit in!</p>
        </div>
      </div>
    </>
  )
}
